// Generated by gencpp from file sim_milliampere/ResetStateRequest.msg
// DO NOT EDIT!


#ifndef SIM_MILLIAMPERE_MESSAGE_RESETSTATEREQUEST_H
#define SIM_MILLIAMPERE_MESSAGE_RESETSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sim_milliampere
{
template <class ContainerAllocator>
struct ResetStateRequest_
{
  typedef ResetStateRequest_<ContainerAllocator> Type;

  ResetStateRequest_()
    : state()  {
    }
  ResetStateRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetStateRequest_

typedef ::sim_milliampere::ResetStateRequest_<std::allocator<void> > ResetStateRequest;

typedef boost::shared_ptr< ::sim_milliampere::ResetStateRequest > ResetStateRequestPtr;
typedef boost::shared_ptr< ::sim_milliampere::ResetStateRequest const> ResetStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sim_milliampere::ResetStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sim_milliampere

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c30e6364d50c603d25671fea66595c53";
  }

  static const char* value(const ::sim_milliampere::ResetStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc30e6364d50c603dULL;
  static const uint64_t static_value2 = 0x25671fea66595c53ULL;
};

template<class ContainerAllocator>
struct DataType< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sim_milliampere/ResetStateRequest";
  }

  static const char* value(const ::sim_milliampere::ResetStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] state\n"
;
  }

  static const char* value(const ::sim_milliampere::ResetStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sim_milliampere::ResetStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sim_milliampere::ResetStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIM_MILLIAMPERE_MESSAGE_RESETSTATEREQUEST_H
