// Generated by gencpp from file sim_milliampere/ResetState.msg
// DO NOT EDIT!


#ifndef SIM_MILLIAMPERE_MESSAGE_RESETSTATE_H
#define SIM_MILLIAMPERE_MESSAGE_RESETSTATE_H

#include <ros/service_traits.h>


#include <sim_milliampere/ResetStateRequest.h>
#include <sim_milliampere/ResetStateResponse.h>


namespace sim_milliampere
{

struct ResetState
{

typedef ResetStateRequest Request;
typedef ResetStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetState
} // namespace sim_milliampere


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sim_milliampere::ResetState > {
  static const char* value()
  {
    return "90925f44bd5df209aa74ed335d36993e";
  }

  static const char* value(const ::sim_milliampere::ResetState&) { return value(); }
};

template<>
struct DataType< ::sim_milliampere::ResetState > {
  static const char* value()
  {
    return "sim_milliampere/ResetState";
  }

  static const char* value(const ::sim_milliampere::ResetState&) { return value(); }
};


// service_traits::MD5Sum< ::sim_milliampere::ResetStateRequest> should match 
// service_traits::MD5Sum< ::sim_milliampere::ResetState > 
template<>
struct MD5Sum< ::sim_milliampere::ResetStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sim_milliampere::ResetState >::value();
  }
  static const char* value(const ::sim_milliampere::ResetStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_milliampere::ResetStateRequest> should match 
// service_traits::DataType< ::sim_milliampere::ResetState > 
template<>
struct DataType< ::sim_milliampere::ResetStateRequest>
{
  static const char* value()
  {
    return DataType< ::sim_milliampere::ResetState >::value();
  }
  static const char* value(const ::sim_milliampere::ResetStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sim_milliampere::ResetStateResponse> should match 
// service_traits::MD5Sum< ::sim_milliampere::ResetState > 
template<>
struct MD5Sum< ::sim_milliampere::ResetStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sim_milliampere::ResetState >::value();
  }
  static const char* value(const ::sim_milliampere::ResetStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sim_milliampere::ResetStateResponse> should match 
// service_traits::DataType< ::sim_milliampere::ResetState > 
template<>
struct DataType< ::sim_milliampere::ResetStateResponse>
{
  static const char* value()
  {
    return DataType< ::sim_milliampere::ResetState >::value();
  }
  static const char* value(const ::sim_milliampere::ResetStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIM_MILLIAMPERE_MESSAGE_RESETSTATE_H
