// Generated by gencpp from file sim_milliampere/ResetStateResponse.msg
// DO NOT EDIT!


#ifndef SIM_MILLIAMPERE_MESSAGE_RESETSTATERESPONSE_H
#define SIM_MILLIAMPERE_MESSAGE_RESETSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sim_milliampere
{
template <class ContainerAllocator>
struct ResetStateResponse_
{
  typedef ResetStateResponse_<ContainerAllocator> Type;

  ResetStateResponse_()
    : success(false)  {
    }
  ResetStateResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetStateResponse_

typedef ::sim_milliampere::ResetStateResponse_<std::allocator<void> > ResetStateResponse;

typedef boost::shared_ptr< ::sim_milliampere::ResetStateResponse > ResetStateResponsePtr;
typedef boost::shared_ptr< ::sim_milliampere::ResetStateResponse const> ResetStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sim_milliampere::ResetStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sim_milliampere

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sim_milliampere::ResetStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sim_milliampere/ResetStateResponse";
  }

  static const char* value(const ::sim_milliampere::ResetStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::sim_milliampere::ResetStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sim_milliampere::ResetStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sim_milliampere::ResetStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIM_MILLIAMPERE_MESSAGE_RESETSTATERESPONSE_H
