(cl:in-package custom_msgs-msg)
(cl:export '(SET_THROTTLE_STOP-VAL
          SET_THROTTLE_STOP
          MOTOR_IN_TEMP_LIMIT-VAL
          MOTOR_IN_TEMP_LIMIT
          BATTERY_NEARLY_EMPTY-VAL
          BATTERY_NEARLY_EMPTY
          MASTER_ERROR_CODE-VAL
          MASTER_ERROR_CODE
          MOTOR_VOLTAGE-VAL
          MOTOR_VOLTAGE
          MOTOR_CURRENT-VAL
          MOTOR_CURRENT
          MOTOR_SPEED-VAL
          MOTOR_SPEED
          MOTOR_PCB_TEMP-VAL
          MOTOR_PCB_TEMP
          MOTOR_STATOR_TEMP-VAL
          MOTOR_STATOR_TEMP
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          BATTERY_CURRENT-VAL
          BATTERY_CURRENT
          TEMPERATURE_REVERSE_VOLTAGE_PROTECTION-VAL
          TEMPERATURE_REVERSE_VOLTAGE_PROTECTION
))