// Generated by gencpp from file supervisor/SwitchMode.msg
// DO NOT EDIT!


#ifndef SUPERVISOR_MESSAGE_SWITCHMODE_H
#define SUPERVISOR_MESSAGE_SWITCHMODE_H

#include <ros/service_traits.h>


#include <supervisor/SwitchModeRequest.h>
#include <supervisor/SwitchModeResponse.h>


namespace supervisor
{

struct SwitchMode
{

typedef SwitchModeRequest Request;
typedef SwitchModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchMode
} // namespace supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::supervisor::SwitchMode > {
  static const char* value()
  {
    return "a418eba3be203821f092a22ffded4941";
  }

  static const char* value(const ::supervisor::SwitchMode&) { return value(); }
};

template<>
struct DataType< ::supervisor::SwitchMode > {
  static const char* value()
  {
    return "supervisor/SwitchMode";
  }

  static const char* value(const ::supervisor::SwitchMode&) { return value(); }
};


// service_traits::MD5Sum< ::supervisor::SwitchModeRequest> should match 
// service_traits::MD5Sum< ::supervisor::SwitchMode > 
template<>
struct MD5Sum< ::supervisor::SwitchModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::supervisor::SwitchMode >::value();
  }
  static const char* value(const ::supervisor::SwitchModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::supervisor::SwitchModeRequest> should match 
// service_traits::DataType< ::supervisor::SwitchMode > 
template<>
struct DataType< ::supervisor::SwitchModeRequest>
{
  static const char* value()
  {
    return DataType< ::supervisor::SwitchMode >::value();
  }
  static const char* value(const ::supervisor::SwitchModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::supervisor::SwitchModeResponse> should match 
// service_traits::MD5Sum< ::supervisor::SwitchMode > 
template<>
struct MD5Sum< ::supervisor::SwitchModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::supervisor::SwitchMode >::value();
  }
  static const char* value(const ::supervisor::SwitchModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::supervisor::SwitchModeResponse> should match 
// service_traits::DataType< ::supervisor::SwitchMode > 
template<>
struct DataType< ::supervisor::SwitchModeResponse>
{
  static const char* value()
  {
    return DataType< ::supervisor::SwitchMode >::value();
  }
  static const char* value(const ::supervisor::SwitchModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPERVISOR_MESSAGE_SWITCHMODE_H
