# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/RemoteControlState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import custom_msgs.msg
import std_msgs.msg

class RemoteControlState(genpy.Message):
  _md5sum = "ceda10c7b37590a99e768bcaea5d1257"
  _type = "custom_msgs/RemoteControlState"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# Custom message to hold the state of the joystick at a given time
# Left stick contains the axis values of the left stick, as a JoyAxis custom message
# Right stick contains the axis values of the right stick, as a JoyAxis custom message
# override_switch holds the position of the override switch, which can be 0, 1 or 2

Header header

custom_msgs/JoyAxis left_stick
custom_msgs/JoyAxis right_stick
uint8 override_switch
uint8 safe_mode
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: custom_msgs/JoyAxis
# Custom message to hold the value of the axes of a joystick

int16 x_axis
int16 y_axis"""
  __slots__ = ['header','left_stick','right_stick','override_switch','safe_mode']
  _slot_types = ['std_msgs/Header','custom_msgs/JoyAxis','custom_msgs/JoyAxis','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,left_stick,right_stick,override_switch,safe_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RemoteControlState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_stick is None:
        self.left_stick = custom_msgs.msg.JoyAxis()
      if self.right_stick is None:
        self.right_stick = custom_msgs.msg.JoyAxis()
      if self.override_switch is None:
        self.override_switch = 0
      if self.safe_mode is None:
        self.safe_mode = 0
    else:
      self.header = std_msgs.msg.Header()
      self.left_stick = custom_msgs.msg.JoyAxis()
      self.right_stick = custom_msgs.msg.JoyAxis()
      self.override_switch = 0
      self.safe_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4h2B().pack(_x.left_stick.x_axis, _x.left_stick.y_axis, _x.right_stick.x_axis, _x.right_stick.y_axis, _x.override_switch, _x.safe_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_stick is None:
        self.left_stick = custom_msgs.msg.JoyAxis()
      if self.right_stick is None:
        self.right_stick = custom_msgs.msg.JoyAxis()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.left_stick.x_axis, _x.left_stick.y_axis, _x.right_stick.x_axis, _x.right_stick.y_axis, _x.override_switch, _x.safe_mode,) = _get_struct_4h2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4h2B().pack(_x.left_stick.x_axis, _x.left_stick.y_axis, _x.right_stick.x_axis, _x.right_stick.y_axis, _x.override_switch, _x.safe_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left_stick is None:
        self.left_stick = custom_msgs.msg.JoyAxis()
      if self.right_stick is None:
        self.right_stick = custom_msgs.msg.JoyAxis()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.left_stick.x_axis, _x.left_stick.y_axis, _x.right_stick.x_axis, _x.right_stick.y_axis, _x.override_switch, _x.safe_mode,) = _get_struct_4h2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4h2B = None
def _get_struct_4h2B():
    global _struct_4h2B
    if _struct_4h2B is None:
        _struct_4h2B = struct.Struct("<4h2B")
    return _struct_4h2B
