// Generated by gencpp from file custom_msgs/ActuatorSetpoints.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ACTUATORSETPOINTS_H
#define CUSTOM_MSGS_MESSAGE_ACTUATORSETPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ActuatorSetpoints_
{
  typedef ActuatorSetpoints_<ContainerAllocator> Type;

  ActuatorSetpoints_()
    : throttle_reference(0)
    , angle_reference(0)  {
    }
  ActuatorSetpoints_(const ContainerAllocator& _alloc)
    : throttle_reference(0)
    , angle_reference(0)  {
  (void)_alloc;
    }



   typedef int16_t _throttle_reference_type;
  _throttle_reference_type throttle_reference;

   typedef int16_t _angle_reference_type;
  _angle_reference_type angle_reference;





  typedef boost::shared_ptr< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorSetpoints_

typedef ::custom_msgs::ActuatorSetpoints_<std::allocator<void> > ActuatorSetpoints;

typedef boost::shared_ptr< ::custom_msgs::ActuatorSetpoints > ActuatorSetpointsPtr;
typedef boost::shared_ptr< ::custom_msgs::ActuatorSetpoints const> ActuatorSetpointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d64702992bfea9b6443fa0b9864979b";
  }

  static const char* value(const ::custom_msgs::ActuatorSetpoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d64702992bfea9bULL;
  static const uint64_t static_value2 = 0x6443fa0b9864979bULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ActuatorSetpoints";
  }

  static const char* value(const ::custom_msgs::ActuatorSetpoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom message for holding the actuator setpoints\n"
"# from thust allocation\n"
"\n"
"int16 throttle_reference\n"
"int16 angle_reference\n"
;
  }

  static const char* value(const ::custom_msgs::ActuatorSetpoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle_reference);
      stream.next(m.angle_reference);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorSetpoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ActuatorSetpoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ActuatorSetpoints_<ContainerAllocator>& v)
  {
    s << indent << "throttle_reference: ";
    Printer<int16_t>::stream(s, indent + "  ", v.throttle_reference);
    s << indent << "angle_reference: ";
    Printer<int16_t>::stream(s, indent + "  ", v.angle_reference);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ACTUATORSETPOINTS_H
