// Generated by gencpp from file custom_msgs/HalfspaceDescription.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_HALFSPACEDESCRIPTION_H
#define CUSTOM_MSGS_MESSAGE_HALFSPACEDESCRIPTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct HalfspaceDescription_
{
  typedef HalfspaceDescription_<ContainerAllocator> Type;

  HalfspaceDescription_()
    : A()
    , b()  {
    }
  HalfspaceDescription_(const ContainerAllocator& _alloc)
    : A(_alloc)
    , b(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _A_type;
  _A_type A;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> const> ConstPtr;

}; // struct HalfspaceDescription_

typedef ::custom_msgs::HalfspaceDescription_<std::allocator<void> > HalfspaceDescription;

typedef boost::shared_ptr< ::custom_msgs::HalfspaceDescription > HalfspaceDescriptionPtr;
typedef boost::shared_ptr< ::custom_msgs::HalfspaceDescription const> HalfspaceDescriptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::HalfspaceDescription_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77bfbd60980c2f9a2cd09f881bcff234";
  }

  static const char* value(const ::custom_msgs::HalfspaceDescription_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77bfbd60980c2f9aULL;
  static const uint64_t static_value2 = 0x2cd09f881bcff234ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/HalfspaceDescription";
  }

  static const char* value(const ::custom_msgs::HalfspaceDescription_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Describes halfspace s.t. Ax <= b is within the halfspace.\n"
"float64[] A\n"
"float64[] b\n"
;
  }

  static const char* value(const ::custom_msgs::HalfspaceDescription_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HalfspaceDescription_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::HalfspaceDescription_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::HalfspaceDescription_<ContainerAllocator>& v)
  {
    s << indent << "A[]" << std::endl;
    for (size_t i = 0; i < v.A.size(); ++i)
    {
      s << indent << "  A[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.A[i]);
    }
    s << indent << "b[]" << std::endl;
    for (size_t i = 0; i < v.b.size(); ++i)
    {
      s << indent << "  b[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.b[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_HALFSPACEDESCRIPTION_H
