// Generated by gencpp from file custom_msgs/ImuSensor.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_IMUSENSOR_H
#define CUSTOM_MSGS_MESSAGE_IMUSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <custom_msgs/orientationEuler.h>
#include <custom_msgs/XsensQuaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct ImuSensor_
{
  typedef ImuSensor_<ContainerAllocator> Type;

  ImuSensor_()
    : header()
    , orientation()
    , dq()
    , dv()
    , angular_velocity()
    , linear_acceleration()  {
    }
  ImuSensor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , orientation(_alloc)
    , dq(_alloc)
    , dv(_alloc)
    , angular_velocity(_alloc)
    , linear_acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::custom_msgs::orientationEuler_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::custom_msgs::XsensQuaternion_<ContainerAllocator>  _dq_type;
  _dq_type dq;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _dv_type;
  _dv_type dv;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;





  typedef boost::shared_ptr< ::custom_msgs::ImuSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ImuSensor_<ContainerAllocator> const> ConstPtr;

}; // struct ImuSensor_

typedef ::custom_msgs::ImuSensor_<std::allocator<void> > ImuSensor;

typedef boost::shared_ptr< ::custom_msgs::ImuSensor > ImuSensorPtr;
typedef boost::shared_ptr< ::custom_msgs::ImuSensor const> ImuSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ImuSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ImuSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImuSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImuSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImuSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImuSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImuSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImuSensor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ImuSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "479b13feb5a2ffdeb7421897e51b76c2";
  }

  static const char* value(const ::custom_msgs::ImuSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x479b13feb5a2ffdeULL;
  static const uint64_t static_value2 = 0xb7421897e51b76c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ImuSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ImuSensor";
  }

  static const char* value(const ::custom_msgs::ImuSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ImuSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"\n"
"Header header\n"
"\n"
"orientationEuler orientation\n"
"\n"
"XsensQuaternion dq\n"
"\n"
"geometry_msgs/Vector3 dv\n"
"\n"
"\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/orientationEuler\n"
"# This is a message to hold orientation data. No header\n"
"\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/XsensQuaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 w\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::ImuSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ImuSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.orientation);
      stream.next(m.dq);
      stream.next(m.dv);
      stream.next(m.angular_velocity);
      stream.next(m.linear_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ImuSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ImuSensor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::custom_msgs::orientationEuler_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "dq: ";
    s << std::endl;
    Printer< ::custom_msgs::XsensQuaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.dq);
    s << indent << "dv: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.dv);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_IMUSENSOR_H
