// Generated by gencpp from file custom_msgs/JoyAxis.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_JOYAXIS_H
#define CUSTOM_MSGS_MESSAGE_JOYAXIS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct JoyAxis_
{
  typedef JoyAxis_<ContainerAllocator> Type;

  JoyAxis_()
    : x_axis(0)
    , y_axis(0)  {
    }
  JoyAxis_(const ContainerAllocator& _alloc)
    : x_axis(0)
    , y_axis(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_axis_type;
  _x_axis_type x_axis;

   typedef int16_t _y_axis_type;
  _y_axis_type y_axis;





  typedef boost::shared_ptr< ::custom_msgs::JoyAxis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::JoyAxis_<ContainerAllocator> const> ConstPtr;

}; // struct JoyAxis_

typedef ::custom_msgs::JoyAxis_<std::allocator<void> > JoyAxis;

typedef boost::shared_ptr< ::custom_msgs::JoyAxis > JoyAxisPtr;
typedef boost::shared_ptr< ::custom_msgs::JoyAxis const> JoyAxisConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::JoyAxis_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::JoyAxis_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::JoyAxis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::JoyAxis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::JoyAxis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::JoyAxis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::JoyAxis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::JoyAxis_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::JoyAxis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8729562965cf2371e2fd83295ee15ec";
  }

  static const char* value(const ::custom_msgs::JoyAxis_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8729562965cf237ULL;
  static const uint64_t static_value2 = 0x1e2fd83295ee15ecULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::JoyAxis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/JoyAxis";
  }

  static const char* value(const ::custom_msgs::JoyAxis_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::JoyAxis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Custom message to hold the value of the axes of a joystick\n"
"\n"
"int16 x_axis\n"
"int16 y_axis\n"
;
  }

  static const char* value(const ::custom_msgs::JoyAxis_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::JoyAxis_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_axis);
      stream.next(m.y_axis);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoyAxis_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::JoyAxis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::JoyAxis_<ContainerAllocator>& v)
  {
    s << indent << "x_axis: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_axis);
    s << indent << "y_axis: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y_axis);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_JOYAXIS_H
