// Generated by gencpp from file custom_msgs/NorthEastHeading.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_NORTHEASTHEADING_H
#define CUSTOM_MSGS_MESSAGE_NORTHEASTHEADING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct NorthEastHeading_
{
  typedef NorthEastHeading_<ContainerAllocator> Type;

  NorthEastHeading_()
    : north(0.0)
    , east(0.0)
    , heading(0.0)  {
    }
  NorthEastHeading_(const ContainerAllocator& _alloc)
    : north(0.0)
    , east(0.0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef double _north_type;
  _north_type north;

   typedef double _east_type;
  _east_type east;

   typedef double _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::custom_msgs::NorthEastHeading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::NorthEastHeading_<ContainerAllocator> const> ConstPtr;

}; // struct NorthEastHeading_

typedef ::custom_msgs::NorthEastHeading_<std::allocator<void> > NorthEastHeading;

typedef boost::shared_ptr< ::custom_msgs::NorthEastHeading > NorthEastHeadingPtr;
typedef boost::shared_ptr< ::custom_msgs::NorthEastHeading const> NorthEastHeadingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::NorthEastHeading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::NorthEastHeading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::NorthEastHeading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::NorthEastHeading_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8c4d8d295356fc4c7989ce2c0e1b148";
  }

  static const char* value(const ::custom_msgs::NorthEastHeading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8c4d8d295356fc4ULL;
  static const uint64_t static_value2 = 0xc7989ce2c0e1b148ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/NorthEastHeading";
  }

  static const char* value(const ::custom_msgs::NorthEastHeading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 north\n"
"float64 east\n"
"float64 heading\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::NorthEastHeading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.north);
      stream.next(m.east);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NorthEastHeading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::NorthEastHeading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::NorthEastHeading_<ContainerAllocator>& v)
  {
    s << indent << "north: ";
    Printer<double>::stream(s, indent + "  ", v.north);
    s << indent << "east: ";
    Printer<double>::stream(s, indent + "  ", v.east);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_NORTHEASTHEADING_H
