// Generated by gencpp from file custom_msgs/SurgeSwayYaw.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_SURGESWAYYAW_H
#define CUSTOM_MSGS_MESSAGE_SURGESWAYYAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct SurgeSwayYaw_
{
  typedef SurgeSwayYaw_<ContainerAllocator> Type;

  SurgeSwayYaw_()
    : surge(0.0)
    , sway(0.0)
    , yaw(0.0)  {
    }
  SurgeSwayYaw_(const ContainerAllocator& _alloc)
    : surge(0.0)
    , sway(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _surge_type;
  _surge_type surge;

   typedef double _sway_type;
  _sway_type sway;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> const> ConstPtr;

}; // struct SurgeSwayYaw_

typedef ::custom_msgs::SurgeSwayYaw_<std::allocator<void> > SurgeSwayYaw;

typedef boost::shared_ptr< ::custom_msgs::SurgeSwayYaw > SurgeSwayYawPtr;
typedef boost::shared_ptr< ::custom_msgs::SurgeSwayYaw const> SurgeSwayYawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d86ccd8ad254d064df2af607e63b6ac0";
  }

  static const char* value(const ::custom_msgs::SurgeSwayYaw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd86ccd8ad254d064ULL;
  static const uint64_t static_value2 = 0xdf2af607e63b6ac0ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/SurgeSwayYaw";
  }

  static const char* value(const ::custom_msgs::SurgeSwayYaw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 surge\n"
"float64 sway\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::custom_msgs::SurgeSwayYaw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.surge);
      stream.next(m.sway);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SurgeSwayYaw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::SurgeSwayYaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::SurgeSwayYaw_<ContainerAllocator>& v)
  {
    s << indent << "surge: ";
    Printer<double>::stream(s, indent + "  ", v.surge);
    s << indent << "sway: ";
    Printer<double>::stream(s, indent + "  ", v.sway);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_SURGESWAYYAW_H
