// Generated by gencpp from file custom_msgs/threeFloats.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_THREEFLOATS_H
#define CUSTOM_MSGS_MESSAGE_THREEFLOATS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct threeFloats_
{
  typedef threeFloats_<ContainerAllocator> Type;

  threeFloats_()
    : setpoint(0.0)
    , state(0.0)
    , error(0.0)  {
    }
  threeFloats_(const ContainerAllocator& _alloc)
    : setpoint(0.0)
    , state(0.0)
    , error(0.0)  {
  (void)_alloc;
    }



   typedef double _setpoint_type;
  _setpoint_type setpoint;

   typedef double _state_type;
  _state_type state;

   typedef double _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::custom_msgs::threeFloats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::threeFloats_<ContainerAllocator> const> ConstPtr;

}; // struct threeFloats_

typedef ::custom_msgs::threeFloats_<std::allocator<void> > threeFloats;

typedef boost::shared_ptr< ::custom_msgs::threeFloats > threeFloatsPtr;
typedef boost::shared_ptr< ::custom_msgs::threeFloats const> threeFloatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::threeFloats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::threeFloats_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::threeFloats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::threeFloats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::threeFloats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::threeFloats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::threeFloats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::threeFloats_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::threeFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fac86045139c18e59f100246b2854728";
  }

  static const char* value(const ::custom_msgs::threeFloats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfac86045139c18e5ULL;
  static const uint64_t static_value2 = 0x9f100246b2854728ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::threeFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/threeFloats";
  }

  static const char* value(const ::custom_msgs::threeFloats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::threeFloats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 setpoint\n"
"float64 state\n"
"float64 error\n"
;
  }

  static const char* value(const ::custom_msgs::threeFloats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::threeFloats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
      stream.next(m.state);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct threeFloats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::threeFloats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::threeFloats_<ContainerAllocator>& v)
  {
    s << indent << "setpoint: ";
    Printer<double>::stream(s, indent + "  ", v.setpoint);
    s << indent << "state: ";
    Printer<double>::stream(s, indent + "  ", v.state);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_THREEFLOATS_H
