// Generated by gencpp from file custom_msgs/ThreeDofForce.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_THREEDOFFORCE_H
#define CUSTOM_MSGS_MESSAGE_THREEDOFFORCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ThreeDofForce_
{
  typedef ThreeDofForce_<ContainerAllocator> Type;

  ThreeDofForce_()
    : X(0.0)
    , Y(0.0)
    , N(0.0)  {
    }
  ThreeDofForce_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , N(0.0)  {
  (void)_alloc;
    }



   typedef double _X_type;
  _X_type X;

   typedef double _Y_type;
  _Y_type Y;

   typedef double _N_type;
  _N_type N;





  typedef boost::shared_ptr< ::custom_msgs::ThreeDofForce_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ThreeDofForce_<ContainerAllocator> const> ConstPtr;

}; // struct ThreeDofForce_

typedef ::custom_msgs::ThreeDofForce_<std::allocator<void> > ThreeDofForce;

typedef boost::shared_ptr< ::custom_msgs::ThreeDofForce > ThreeDofForcePtr;
typedef boost::shared_ptr< ::custom_msgs::ThreeDofForce const> ThreeDofForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ThreeDofForce_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/eivinddm/milliAmpere/workspace/src/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ThreeDofForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ThreeDofForce_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ThreeDofForce_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d59525997a21f5b026ea2746ebcfb38";
  }

  static const char* value(const ::custom_msgs::ThreeDofForce_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d59525997a21f5bULL;
  static const uint64_t static_value2 = 0x026ea2746ebcfb38ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ThreeDofForce";
  }

  static const char* value(const ::custom_msgs::ThreeDofForce_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 X\n"
"float64 Y\n"
"float64 N\n"
;
  }

  static const char* value(const ::custom_msgs::ThreeDofForce_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.N);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThreeDofForce_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ThreeDofForce_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ThreeDofForce_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<double>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<double>::stream(s, indent + "  ", v.Y);
    s << indent << "N: ";
    Printer<double>::stream(s, indent + "  ", v.N);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_THREEDOFFORCE_H
